# Generated by Django 2.2.5 on 2019-10-12 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='preview/')),
                ('picture', models.ImageField(upload_to='')),
                ('media_type', models.CharField(choices=[('S', 'Style'), ('C', 'Content'), ('M', 'Model'), ('R', 'Result')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_result_media', to='app.Media_Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_media', to='app.Media_Model')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_media', to='app.Media_Model')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_media', to='app.Media_Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
